import numpy as np
from msdsl import *
m = MixedSignalModel('model')
t = m.add_analog_input('t')
y = m.add_analog_output('y')
func1 = lambda t: np.sin(t)
func2 = lambda t: np.cos(t)
func3 = lambda t: np.tan(t)
f1 = m.make_function(func1, domain=[-np.pi, np.pi], numel=512, order=1)
f2 = m.make_function(func2, domain=[-np.pi, np.pi], numel=512, order=1)
f3 = m.make_function(func3, domain=[-np.pi/4, np.pi/4], numel=512, order=1)
a1 = m.set_from_sync_func('a1', f1, t)
a2 = m.set_from_sync_func('a2', f2, t)
a3 = m.set_from_sync_func('a3', f2, t)
m.set_this_cycle(y, a3*(a1-a2))
m.compile_and_print(VerilogGenerator())